---
- hosts: proxmox
  gather_facts: false
  roles:
    - win2k19_base_template
    - primary_dc_build
    - replica_dc_build

- hosts: primary_dc_vm
  gather_facts: false
  roles:
    - common
    - primary_dc_provision

- hosts: replica_dc_vm
  gather_facts: false
  roles:
    - common
    - replica_dc_provision